### ISSUE TITLE
Ability to test whether warnings are raised during test steps

### ISSUE THREAD

**Issue by bendbennett** [hashicorp/terraform-plugin-testing#16] opened 2023-01-03 10:49 UTC
This issue is a duplicate of [Ability to test whether warnings are raised during test steps](https://github.com/hashicorp/terraform-plugin-testing/issues/69). 

### Version
N/A

### Use-cases
Currently, ExpectError [field](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/helper/resource#TestStep) only allows checking errors, not warnings. This makes provider developers hard to test certain scenarios where warnings are expected and want to validate the exact behavior in tests.

### Attempted Solutions
N/A

### Proposal
Add an `ExpectWarning` field to `TestStep` and use json output from terraform commands to determine whether warnings have been generated during execution of a test step.

Requires changes to [terraform-exec](https://github.com/hashicorp/terraform-exec) to add support for executing terraform commands with `-json` option (see References below for links to relevant issue and PRs on [terraform-exec repository](https://github.com/hashicorp/terraform-exec).

### References
- https://discuss.hashicorp.com/t/how-to-test-warnings/34259
- [Plan/Apply -json support missing](https://github.com/hashicorp/terraform-exec/issues/183#top)
- [Add JSON option for "plan" and "apply"](https://github.com/hashicorp/terraform-exec/pull/275#top)
- [json log for plan and apply](https://github.com/hashicorp/terraform-exec/pull/329#top)

**Comment by bflad** [comment] 2023-02-28 20:23
Closing as a duplicate of the (now transferred) #69.

**Closed by bflad** 2023-02-28 20:23 UTC
Labels: enhancement
