### ISSUE TITLE
resource.TestCheckNoResourceAttr() fails even though the resource is supposed to be deleted

### ISSUE THREAD

**Issue by kvaidas** [hashicorp/terraform-plugin-testing#357] opened 2024-06-26 21:02 UTC
### terraform-plugin-testing version
```
github.com/hashicorp/terraform-plugin-testing v1.8.0
```

### Relevant provider source code
[provider code](https://github.com/kvaidas/terraform-provider-httpclient/blob/44c47c5840be28085b6e0aadf5dd5ca204d976a6/internal/provider/resource_test.go#L105)

### Terraform Configuration Files

```tf
In the test code, linked above.
```

### Expected Behavior
Test should succeed since the delete resource API call is being sent.
Running this provider using Terraform (as a user) works as expected, resource in the state file also is deleted.

### Actual Behavior
Fails with the following error:
```
resource_test.go:109: Error running post-test destroy, there may be dangling resources: Check 1/1 error: httpclient_resource.test-resource: Attribute 'variables.name' found when not expected
```

### Steps to Reproduce
run `TF_ACC=1 go test -v ./...`

### References
None

**Comment by austinvalle** [comment] 2024-07-18 16:30
Hey @kvaidas 👋🏻, thanks for providing that example and sorry you're running into trouble here.

The `CheckDestroy` function is useful for a provider to test that the resource doesn't exist _in the remote system_, not Terraform state. Since the state value for a resource after destroy will always be null (you don't really need to test this, since Terraform core handles this logic), `CheckDestroy` passes the [last state value](https://github.com/hashicorp/terraform-plugin-testing/blob/23a9124b59be2685af2f953ceeb09eb0222824ce/helper/resource/testing_new.go#L37-L46) prior to the destroy command being run. So your test is actually running on an old version of state, checking that the attribute was null before the resource was actually destroyed.

Usually this old state in `CheckDestroy` is used to extract an ID and check the remote system to make sure it doesn't exist. Here's an example with the AWS tag resource:

- https://github.com/hashicorp/terraform-provider-aws/blob/e905e90bd8c06aed9c830884c34fde9ec0cb49d2/internal/service/ec2/tag_test.go#L27
- https://github.com/hashicorp/terraform-provider-aws/blob/e905e90bd8c06aed9c830884c34fde9ec0cb49d2/internal/service/ec2/tag_gen_test.go#L19-L48

With that being said, I believe `CheckDestroy` is operating as intended, so I'm going to close this issue. Let me know if I missed anything!

**Closed by austinvalle** 2024-07-18 16:30 UTC
Labels: bug
